### PR TITLE
README with the right commands

### PR DESCRIPTION
**Pull request by c4f3firstt**

### CODE REVIEW

**Comment by nandydark** [comment]
Ahhh yes.. i literally never used any command after copy pasting it from  repo.. but yeah thanks for pointing out this.. some kiddies must had problem with it

**Comment by c4f3firstt** [comment]
I was thinking about creating a script to make a easier instalation of selenium

**Comment by c4f3firstt** [comment]
You closed my request and changed anyway? This was really shady

**Comment by nandydark** [comment]
Yeah i closed it because it's completely pointless and i am currently working on many project.. so i don't think i can waste my time in adding or correcting the commands for kiddies or whatever... and if you're thinking to create a script to easily install selenium.. then yeah you can.. if you needed any of my help or whatever you can contact me through my portfolio

**Pull request closed without merging**
